services:
  # Angular Frontend with Nginx
  website:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: production
    container_name: website
    restart: always
    ports:
      - "80:80"