services:
  order-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: order-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/food-order?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SPRING_FLYWAY_VALIDATE_ON_MIGRATE: false
      SPRING_DATA_REDIS_HOST: redis
      SPRING_PROFILES_ACTIVE: docker
    command: >
      /bin/bash -c "
        apt-get update && 
        apt-get install -y wget && 
        wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && 
        tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && 
        mv dockerize /usr/local/bin/ && 
        dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s && 
        java -jar /app/app.jar
      "

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food-order
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes:
  mysql_data:
  redis_data: